# Generated by Django 4.0 on 2023-08-15 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal_profile',
            fields=[
                ('animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_no', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('weight', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('purchase_price', models.IntegerField(null=True)),
                ('purchased_by', models.CharField(blank=True, max_length=50, null=True)),
                ('purchased_on', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('description', models.TextField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('is_pragnent', models.IntegerField(null=True)),
                ('pragnancy_start_date', models.DateField(blank=True, null=True)),
                ('pragnancy_end_date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('updated_on', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PregnancyDetails',
            fields=[
                ('Pregnancy_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('is_pregnancy_confirmed', models.BooleanField(blank=True, null=True)),
                ('pregnancy_checked_on', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_delivery_completed', models.BooleanField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('is_miscarriage', models.BooleanField(blank=True, null=True)),
                ('miscarriage_date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('updated_on', models.DateField(blank=True, null=True)),
                ('animal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals_id', to='livestockapp.animal_profile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_by', to='livestockapp.animal_profile')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_by', to='livestockapp.animal_profile')),
            ],
        ),
        migrations.AddField(
            model_name='animal_profile',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='livestockapp.category'),
        ),
    ]
