# Generated by Django 4.0 on 2023-08-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregnancydetails',
            old_name='animal_id',
            new_name='animal',
        ),
    ]
