# Generated by Django 4.0.5 on 2023-09-09 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livestockapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('account_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('main_code', models.CharField(max_length=10, null=True)),
                ('sub_code', models.CharField(max_length=10, null=True)),
                ('dept_code', models.CharField(max_length=10, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('account_type', models.CharField(max_length=100, null=True)),
                ('is_account', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_accounts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RefVoucherType',
            fields=[
                ('voucher_type_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, null=True)),
                ('is_enabled', models.CharField(max_length=1, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_ref_voucher_type', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_ref_voucher_type', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherMain',
            fields=[
                ('trans_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('voucher_no', models.CharField(max_length=100, null=True)),
                ('voucher_date', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_voucher_main', to=settings.AUTH_USER_MODEL)),
                ('ref_voucher_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_main', to='livestockapp.refvouchertype')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_voucher_main', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=3, max_digits=13, null=True)),
                ('credit', models.DecimalField(decimal_places=3, max_digits=13, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('chart_of_account', models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_detail', to='livestockapp.chartofaccount')),
                ('voucher_main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_detail', to='livestockapp.vouchermain')),
            ],
        ),
        migrations.CreateModel(
            name='RefPartyType',
            fields=[
                ('party_type_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, null=True)),
                ('is_enabled', models.CharField(max_length=1, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_ref_party_type', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_ref_party_type', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RefPartyProfile',
            fields=[
                ('party_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('ntn_no', models.CharField(max_length=50, null=True)),
                ('phone_no', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('payment_terms', models.CharField(max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('chart_of_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_party_profile', to='livestockapp.chartofaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_ref_party_profile', to=settings.AUTH_USER_MODEL)),
                ('ref_party_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_profile', to='livestockapp.refpartytype')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_ref_party_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
