# Generated by Django 4.0 on 2023-07-24 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal_profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token_no', models.IntegerField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('purchase_price', models.IntegerField(max_length=50)),
                ('purchased_by', models.IntegerField(max_length=50)),
                ('purchased_on', models.DateTimeField(blank=True, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=50)),
                ('is_pragnent', models.IntegerField(blank=True, null=True)),
                ('pragnancy_start_date', models.DateTimeField(blank=True, null=True)),
                ('pragnancy_end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(max_length=50)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='livestockapp.category')),
            ],
        ),
    ]
