# Generated by Django 4.0 on 2023-07-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_profile',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
