# Generated by Django 4.0 on 2023-09-01 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal_profile',
            name='is_pregnant',
        ),
        migrations.RemoveField(
            model_name='animal_profile',
            name='pregnancy_end_date',
        ),
        migrations.RemoveField(
            model_name='animal_profile',
            name='pregnancy_start_date',
        ),
        migrations.RemoveField(
            model_name='pregnancydetails',
            name='expected_end_date',
        ),
        migrations.RemoveField(
            model_name='pregnancydetails',
            name='start_date',
        ),
    ]
