# Generated by Django 4.0.5 on 2023-09-11 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livestockapp', '0002_chartofaccount_refvouchertype_vouchermain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInHand',
            fields=[
                ('stock_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('sale_price', models.DecimalField(decimal_places=3, max_digits=13, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=3, max_digits=13, null=True)),
                ('stock_in_hand', models.CharField(max_length=18, null=True)),
                ('order_threshold', models.CharField(max_length=18, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_stock_in_hand', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockType',
            fields=[
                ('stock_type_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('is_enabled', models.CharField(max_length=1, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_stock_type', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_stock_type', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockSaleMain',
            fields=[
                ('invoice_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_stock_sale_main', to=settings.AUTH_USER_MODEL)),
                ('ref_party_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_sale_main', to='livestockapp.refpartyprofile')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_stock_sale_main', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockSaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=13, null=True)),
                ('stock_in_hand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_sale_detail', to='livestockapp.stockinhand')),
                ('stock_sale_main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_detail', to='livestockapp.stocksalemain')),
            ],
        ),
        migrations.CreateModel(
            name='StockPurchaseMain',
            fields=[
                ('bill_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Bill_date', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_stock_purchase_main', to=settings.AUTH_USER_MODEL)),
                ('ref_party_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_purchase_main', to='livestockapp.refpartyprofile')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_stock_purchase_main', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockPurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=13, null=True)),
                ('stock_in_hand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_purchase_detail', to='livestockapp.stockinhand')),
                ('stock_purchase_main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_detail', to='livestockapp.stockpurchasemain')),
            ],
        ),
        migrations.AddField(
            model_name='stockinhand',
            name='stock_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_in_hand', to='livestockapp.stocktype'),
        ),
        migrations.AddField(
            model_name='stockinhand',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_stock_in_hand', to=settings.AUTH_USER_MODEL),
        ),
    ]
