# Generated by Django 4.0 on 2023-08-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0002_rename_animal_id_pregnancydetails_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancydetails',
            name='is_delivery_completed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='pregnancydetails',
            name='is_pregnancy_confirmed',
            field=models.BooleanField(null=True),
        ),
    ]
