# Generated by Django 4.0 on 2023-09-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0002_remove_animal_profile_is_pregnant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='joinTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_no', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_pregnant', models.IntegerField(null=True)),
            ],
        ),
    ]
