# Generated by Django 4.0 on 2023-07-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0002_alter_animal_profile_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_profile',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal_profile',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal_profile',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='animal_profile',
            name='is_pragnent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animal_profile',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal_profile',
            name='purchase_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animal_profile',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal_profile',
            name='token_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal_profile',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal_profile',
            name='weight',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
