# Generated by Django 4.0.5 on 2023-07-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0002_animal_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_profile',
            name='purchase_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='animal_profile',
            name='purchased_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='animal_profile',
            name='token_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='animal_profile',
            name='updated_by',
            field=models.IntegerField(),
        ),
    ]
