# Generated by Django 4.0 on 2023-08-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0003_alter_pregnancydetails_is_delivery_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnancydetails',
            name='infartility',
            field=models.BooleanField(null=True),
        ),
    ]
