# Generated by Django 4.0 on 2023-09-01 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0003_jointables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jointables',
            old_name='token_no',
            new_name='animal_id',
        ),
    ]
