# Generated by Django 4.0.5 on 2023-09-11 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0003_stockinhand_stocktype_stocksalemain_stocksaledetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal_profile',
            name='purchased_by',
        ),
        migrations.AddField(
            model_name='animal_profile',
            name='ref_party_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_pro', to='livestockapp.refpartyprofile'),
        ),
        migrations.AddField(
            model_name='stockpurchasedetail',
            name='animal_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_purchase_detail', to='livestockapp.animal_profile'),
        ),
    ]
