# Generated by Django 4.0 on 2023-07-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0003_alter_animal_profile_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_profile',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
