# Generated by Django 4.0 on 2023-08-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0004_pregnancydetails_infartility'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnancydetails',
            name='is_pragnent',
            field=models.IntegerField(null=True),
        ),
    ]
