# Generated by Django 4.0 on 2023-08-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0004_alter_animal_profile_updated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal_profile',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='animal_profile',
            name='purchased_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
