# Generated by Django 4.0 on 2023-08-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0005_pregnancydetails_is_pragnent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnancydetails',
            name='pragnancy_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnancydetails',
            name='pragnancy_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
