# Generated by Django 4.2.5 on 2023-09-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0005_alter_animal_profile_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal_profile',
            name='is_shared',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
