# Generated by Django 4.0 on 2023-08-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0005_rename_category_id_animal_profile_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_profile',
            name='created_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal_profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal_profile',
            name='is_pragnent',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='animal_profile',
            name='pragnancy_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal_profile',
            name='pragnancy_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal_profile',
            name='purchased_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal_profile',
            name='updated_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
