# Generated by Django 4.0 on 2023-08-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0006_alter_animal_profile_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_profile',
            name='is_pragnent',
            field=models.IntegerField(null=True),
        ),
    ]
