# Generated by Django 4.2.5 on 2023-10-02 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livestockapp', '0006_animal_profile_is_shared'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareAnimal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField(null=True)),
                ('payment_date', models.DateTimeField(null=True)),
                ('payment', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('updated_on', models.DateField(blank=True, null=True)),
                ('animal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_profile', to='livestockapp.animal_profile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Updated_animal_profile', to=settings.AUTH_USER_MODEL)),
                ('party_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_profile', to='livestockapp.refpartyprofile')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Updated_animals_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
