# Generated by Django 4.2.5 on 2023-10-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0007_shareanimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareanimal',
            name='month',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
