# Generated by Django 4.0.5 on 2023-10-02 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0008_remove_animal_profile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal_profile',
            name='ref_party_profile',
        ),
    ]
