# Generated by Django 4.2.5 on 2023-10-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0008_alter_shareanimal_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareanimal',
            name='payment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
