# Generated by Django 4.0.5 on 2023-10-02 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0009_remove_animal_profile_ref_party_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal_profile',
            old_name='purchased_party_id',
            new_name='purchased_party',
        ),
        migrations.RenameField(
            model_name='animal_profile',
            old_name='shared_party_id',
            new_name='shared_party',
        ),
        migrations.RemoveField(
            model_name='animal_profile',
            name='is_shared',
        ),
        migrations.AddField(
            model_name='animal_profile',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_parent', to='livestockapp.animal_profile'),
        ),
    ]
