# Generated by Django 4.0.5 on 2023-10-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0010_rename_purchased_party_id_animal_profile_purchased_party_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_profile',
            name='token_no',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
