# Generated by Django 4.0.5 on 2023-10-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0009_alter_shareanimal_payment'),
        ('livestockapp', '0011_alter_animal_profile_token_no'),
    ]

    operations = [
    ]
